//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace diary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int diary_id { get; set; }
        public string diary_title { get; set; }
        public string diary_content { get; set; }
        public string diary_subtime { get; set; }
        public int diary_author_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
